name: test condition 
on: [push,workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest 
    steps:
      - name: Get Code
        uses: actions/checkout@v7
      - name: cashing requierments
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{hashFiles('requirements.txt')}}
      - name: install Python 
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'    
      - name: install reiquirments
        run: pip install -r requirements.txt
      - name: run test data quality
        id: test_data_quality
        run: pytest tests/test_data_quality.py
      - name: print failuer message
        if: steps.test_data_quality.outcome == 'failure'
        run: echo "Data Quality step has failed"
      - name: generate artifact
        run: python build_output.py
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: transformed_data
          path: |
            data/clean_sales.csv
            data/sales_by_category.csv
 