name: test condition 
on: [push,workflow_dispatch]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9','3.10','3.11']
        os: ['ubuntu-latest','windows-latest']
        exclude:
          - python-version: '3.9'
            os: 'ubuntu-latest'
        include:
          - python-version: '3.12'
            os: 'ubuntu-latest'
         

    runs-on: ${{matrix.os}}
    steps:
      - name: Get Code
        uses: actions/checkout@v7
      - name: cashing requierments
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip_requirments_${{hashFiles('requirements.txt')}}
      - name: install Python 
        uses: actions/setup-python@v6
        with:
          python-version: ${{matrix.python-version}}
      - name: install reiquirments
        run: pip install -r requirements.txt
