name: test_job
on:
  workflow_call:
    inputs:
      python-version:
        type: string
        description: "version of python"
        required: false
        default: '3.9'
      test-file:
        type: string
jobs:
  test_reusabel:
    runs-on: ubuntu-latest 
    steps:
      - name: Get Code
        uses: actions/checkout@v7
      - name: install Python 
        uses: actions/setup-python@v6
        with:
          python-version: ${{inputs.python-version}} 
      - name: caching requirments
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip 
          key: pip_requirments_${{hashFiles('requirements.txt')}}
      - name: install requirments
        run: pip install -r requirements.txt
      - name: run test data quality 
        run: pytest ${{inputs.test-file}}